<div>
    <a href="<?= URL ?>order/cartOrder?cartId=<?= $cart->id ?>&price=<?= $cart->price ?>" class="btn"
       <?php if(!(float)$cart->price): ?>
       onclick="return alert('Your cart is empty!')"
       <?php endif; ?>
    >Make Order</a>
    Total price: <?= $cart->price ?> €
</div>

<table class="table">
    <thead>
    <tr>
        <th>Image</th>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Amount</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach($data as $row){
        include 'table.phtml';
    }
    ?>
    </tbody>
</table>
