<tr>
    <td title="Image">
        <img style="width: min-content; height: min-content" src="<?= $row->image ?>" alt="Product image" />
    </td>
    <td title="Name"><?= $row->name?></td>
    <td title="Description"><?= $row->description ?></td>
    <td title="Price"><?= $row->price ?></td>
    <td title="Amount"><?= $row->amount ?></td>
    <td title="Action">
        <a href="/cart/removeProductFromCart?productId=<?= $row->id ?>">
            <i class="fas fa-times fa-2x"></i>
        </a>
    </td>
</tr>
