<table class="table">
    <thead>
    <tr>
        <th>Order Number</th>
        <th>Time ordered</th>
        <th>Price</th>
        <th>Status</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
        <?php
            foreach($orderData as $orderRow){
                if ($orderRow->user === $_SESSION['user']->id || $_SESSION['user']->status !== 'Guest'){
                    include 'table.phtml';
                }
            }
        ?>
    </tbody>
</table>
