<tr>
    <td title="Image">
        <img style="width: min-content; height: min-content" src="<?= $productRow['image'] ?>" alt="Product image" />
    </td>
    <td title="Name"><?= $productRow['name'] ?></td>
    <td title="Description"><?= $productRow['description'] ?></td>
    <td title="Price"><?= $productRow['price'] ?></td>
    <td title="Amount"><?= $productRow['amount'] ?></td>
</tr>
