<div class="col-sm-3">
    <div class="card">
        <img class="card-img-top" src="..." alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title"><?=  $product->name ?></h5>
            <p class="card-text"><?=  $product->description ?></p>
            <p> <?=  $product->price ?> </p>

                <i
                    class="fas fa-cart-plus fa-2x"
                    data-productId="<?=  $product->id ?>"
                    data-productName="<?=  $product->name ?>"
                    data-toggle="modal" data-target="#myModal">
                </i>

        </div>
    </div>
</div>