<div class="col-sm-3">
    <div class="card">
        <img class="card-img-top" src="..." alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title"><?=  $product->name ?></h5>
            <p class="card-text"><?=  $product->description ?></p>
            <p> <?=  $product->price ?> </p>
            <a href="#" class="card-link"><i class="fas fa-cart-plus fa-2x"></i></a>
        </div>
    </div>
</div>