<form class="forms" method="POST" action="<?=URL?>product/submitEditProduct" enctype="multipart/form-data">

    <div class="form-group">
        <label for="name"> Name </label>
        <input type="text" class="form-control" name="name" value="<?= $product->name ?>">
    </div>

    <div class="form-group">
        <label for="description">Description </label>
        <input type="text" class="form-control" name="description" value="<?= $product->description ?>">
    </div>

    <div class="form-group">
        <label for="category">Category</label>
        <select class="form-control" name="category">
            <?php foreach($categories as $cat):?>
                <option <?php if($product->category == $cat->id) echo 'selected'?>
                        value="<?= $cat->id ?>"><?= $cat->name ?></option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="form-group">
        <label for="price"> Price </label>
        <input type="number" class="form-control" name="price" step=".01" value="<?= $product->price ?>">
    </div>

    <div class="form-group">
        <label for="image"> Image </label>
        <input type="file" name="image">
    </div>

    <div>
        <input type="hidden" name="id" value="<?= $product->id ?>">
        <a href="<?=URL?>product/menu" class="btn"> Back </a>
        <input type="submit" class="btn" value="Edit">
    </div>
</form>
