<?php
if (isset($message)) echo $message;
if ($currentUser && $currentUser->status === 'Admin'): ?>
    <a href="/product/addNewProduct" class="btn btn-primary">Add new product</a>
<?php endif; ?>
<?php foreach ($categories as $cat ): ?>

    <h3><?= $cat->name ?></h3>
    <?php include 'cards.phtml' ?>

<?php endforeach; ?>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="question"></h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                Choose amount !
                <input id="amount" type="number" value="1">
            </div>
            <div class="modal-footer">
                <a id="addLink" class="btn btn-success" >Add</a>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
