<form method="POST" action="/admin/submitEditUser?id=<?= $user->id ?>">

    <div class="form-group">
        <label for="first_name"> First Name </label>
        <input type="text" class="form-control" name="first_name" value="<?= $user->first_name ?>">
    </div>

    <div class="form-group">
        <label for="last_name"> Last Name </label>
        <input type="text" class="form-control" name="last_name" value="<?= $user->last_name ?>">
    </div>

    <div class="form-group">
        <label for="email"> Email </label>
        <input type="email" class="form-control" name="email" value="<?= $user->email ?>">
    </div>

    <div class="form-group">
        <label for="status"> Status </label>
        <input type="text" class="form-control" name="status" value="<?= $user->status ?>">
    </div>

    <div class="form-group">
        <label for="password"> Password </label>
        <input type="password" class="form-control" name="password">
    </div>

    <div class="form-group">
        <label for="confirm_password">Confirm Password</label>
        <input type="password" class="form-control" name="confirm_password">
    </div>

    <div>
        <a href="/admin/userCrud" class="btn btn-danger"> Back </a>
        <input type="submit" class="btn btn-success" value="Edit">
    </div>
</form>
