
<a href="<?= URL ?>order/order" class="btn"> Back </a>
<a href="<?= URL ?>staff/addNewProduct?cartId=<?= $cart->id?>" class="btn"> Add new product </a>

<table class="table">
    <thead>
    <tr>
        <th>Image</th>
        <th>Name</th>
        <th>Amount</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach($orderInfo as $product){
        include 'table.phtml';
    }
    ?>
    </tbody>
</table>
