<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
            </li>
            <?php if ($currentUser === null): ?>
                <li class="nav-item">
                    <a class="nav-link" href="/user/login">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/user/register">Register</a>
                </li>
            <?php else: ?>
                <li class="nav-item">
                    <a class="nav-link" href="/user/logout">Logout</a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
</nav>