<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link navbar-brand" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-brand" href="/home/about">About Us</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-brand" href="/product/menu">Menu</a>
            </li>
            <?php if ($currentUser && $currentUser->status === 'Admin'): ?>
                <li class="nav-item">
                    <a class="nav-link navbar-brand" href="/admin/userCrud">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navbar-brand" href="/admin/category">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navbar-brand" href="/admin/status">Status</a>
                </li>
            <?php endif; ?>
            <li class="nav-item">
                <a class="nav-link navbar-brand" href="/order/order">Orders</a>
            </li>
            <?php if ($currentUser && $currentUser->status === 'Guest'): ?>
            <li class="nav-item">
                <a class="nav-link" href="/cart/cart"><i class="fas fa-shopping-cart fa-2x"></i></a>
            </li>
            <?php endif; ?>
        </ul>
        <ul class="navbar-nav">
            <?php if ($currentUser && $currentUser->status === 'Guest' && $currentUser->email !== 'noLogin@user.com'): ?>
                <?php if($currentUser->points > \App\Core\Config::get('points')):?>
                    <li>
                        <p class="points"> You have discount! </p>
                    </li>
                <?php endif; ?>
                <li class="nav-item">
                    <p class="points"> Points:  <?= $currentUser->points ?> </p>
                </li>

            <?php endif; ?>
            <?php if ($currentUser === null): ?>
                <li class="nav-item">
                    <a class="nav-link navbar-brand" href="/user/login">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navbar-brand" href="/user/register">Register</a>
                </li>
            <?php else: ?>
                <li class="nav-item">
                    <a class="nav-link navbar-brand" href="/user/logout">Logout</a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
</nav>