<?php include 'layout/header.phtml' ?>

<h1>About Us</h1>

<p> Colletta’s cuisine draws influence largely from Northern Italy, putting a twist on
    treasured classics and introducing modern culinary techniques with the changing of
    the seasons. House-made pastas, cheeses and other hand-crafted ingredients abound in
    the from-scratch kitchen, and guests will taste the culinary team’s attention to
    detail in every bite. Staying true to Italian dining traditions, Colletta also offers
    a “For the Table” dining option that allows for a fun, family-style experience, offered
    nightly alongside the full à la carte menu.</p>

<p>
    The restaurant’s open-concept dining room is anchored around the kitchen’s wood-burning oven,
    reminiscent of the hearth in a family home. Accented by reclaimed barn wood and refined ceramic tile,
    the modern space envelops guests in a welcoming atmosphere – whether they’re visiting the bar
    for a hand-crafted cocktail or a glass of wine,
    grabbing a pizza with the kids or sitting down for a family-style dinner with friends and colleagues.</p>


<?php include 'layout/footer.phtml' ?>