<form class="forms" method="post" action="<?=URL?>user/loginSubmit">
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" name="email">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" name="password">
    </div>
    <button type="submit" class="btn">Login</button>
    <a class="btn" href="<?=URL?>user/withoutLogin">Continue without login</a>
    <p><a href="<?=URL?>user/register">Don't have account ? Register</a></p>
</form>
