<?php
    if(file_exists(BP . 'images' . DIRECTORY_SEPARATOR .
        'users' . DIRECTORY_SEPARATOR . $currentUser->id . '.png')): ?>

    <img style="max-width: 200px"
         src="<?= \App\Core\Config::get('url') ?>images/users/<?= $currentUser->id ?>.png"
        alt="Profile image" />

<?php else:?>
    <img style="max-width: 200px"
         src="<?= \App\Core\Config::get('url') ?>images/users/unknownProfile.png"
         alt="Profile picture not set" />
<?php endif;?>

<h3><?= $currentUser->first_name . ' ' . $currentUser->last_name  ?></h3>
<p><?= $currentUser->email ?></p>
